import { cn } from "@/shared/utils/shadcn/utils";
import type { Metadata } from "next";
import { Instrument_Sans, Roboto } from "next/font/google";
import NextTopLoader from "nextjs-toploader";
import { Toaster } from "sonner";
import "./globals.css";
const instrumentSansHeading = Instrument_Sans({
  subsets: ["latin"],
  variable: "--font-heading",
});

const roboto = Roboto({ subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn(
        "font-sans",
        roboto.variable,
        instrumentSansHeading.variable,
      )}
    >
      <body className={`antialiased`}>
        <NextTopLoader color="oklch(0.508 0.118 165.612)" />
        <Toaster />
        {children}
      </body>
    </html>
  );
}
